### ISSUE TITLE
myScope(); is not a function

### ISSUE THREAD

**Issue by bdacoscos** [learn-co-curriculum/skills-based-js-scope#14]
In the Closure section, fourth code snippet: Shouldn't `myScope(); ` be `myScope;`? It is not a function, but just a variable that stores the function `outerFunction()`.

**Comment by gj** [comment]
Hi @bdacoscos !

It's correct as-is. Because it points at a function (`innerFunction()`, which was the return value when we invoked `outerFunction()`), by 'invoking' the variable we're invoking the function that it points at.
