### ISSUE TITLE
I don't understand what "stringified version of outerFunction" means exactly

### ISSUE THREAD

**Issue by yaakovbeiss** [learn-co-curriculum/skills-based-js-scope#15]
I read the lesson and I am trying to understand exactly what the difference is between calling the outerFunction and calling the myScope instance of the outerFunction function. I know that myScope returns "I'm sort of a secret" while outerScope() just returns the function innerScope(), but I am not sure why that is. I think it has something to do with the fact that outerFunction() gets stringified by myScope. If someone could explain this I would greatly appreciate it. Thanks.

**Comment by JessRudder** [comment]
HI @yaakovbeiss if you still have questions about this you should use the "Ask a Question" feature in Learn to get help from a Learn Expert.
