### ISSUE TITLE
JS Scope

### ISSUE THREAD

**Issue by jesschip38** [learn-co-curriculum/skills-based-js-scope#7]
When I define the variable as either:

var y = 2

or

y = 2

within the brackets of a function, I cannot call console.log(y) outside of the function.  As described in the lesson, I should be able to call console.log(y) outside of the function if I define the variable y as

y = 2

within the brackets of the function.  However, I must define the variable y = 2 **_outside_** of the function brackets in order to call console.log(y) outside of the function.

![example jc console 10 3 16](https://cloud.githubusercontent.com/assets/22501015/19042296/76e9d5a4-8959-11e6-8717-f47741135764.png)

**Comment by AnnJohn** [comment]
hi @jesschip38 this might be an issue specific to you so could you use Ask a Question in Learn and someone from our instructional support team will help you out. If it is a larger issue, then they'll raise another issue here. thanks!
